### ISSUE TITLE
Usando información sobre Covid-19 para aprender.r #YoMeQuedoEnCasa

### ISSUE THREAD

**Issue by neosergio** [peruanosdev/playlist-quarantine-edition#10]
## Titulo de la charla 
IDEAS durante cuarentena: Usar información sobre Covid-19 para aprender #YoMeQuedoEnCasa, video 03

## Descripcion
Ideas para hacer durante la cuarentena: Usar la información disponible sobre Covid-19 para aprender a procesar datos, manejar datasets, mejorar tus habilidades en estadística, hacer alguna app que use esa información, y lo que se te ocurra. #YoMeQuedoEnCasa

## Enlace del video ( YouTube )
https://www.youtube.com/watch?v=6VlVqXz-m5A

**Comment by neosergio** [comment]
Título del video: Usando información sobre Covid-19 para aprender.

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
