### ISSUE TITLE
Greenter

### ISSUE THREAD

**Issue by FraGoTe** [peruanosdev/playlist-quarantine-edition#11]
## Titulo de la charla 
Greenter - Facturación Electrónica
## Descripcion
Esta libreria le permite realizar la implementación de la Facturación Electrónica en Perú, desde los sistemas desarrollados por el contribuyente, la cual esta normado por SUNAT.
Greenter realiza la mayoria de tareas del proceso, genera el XML según el estándar UBL, firma con el certificado digital que sunat exige, comprime el archivo XML en formato zip, conexión al webservice de SUNAT y procesa el CDR (Comprobante de Recepción).
## Enlace del video ( YouTube )
https://www.youtube.com/watch?v=u69SWWdiReQ

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
