### ISSUE TITLE
Introducción a Machine Learning con Kaggle

### ISSUE THREAD

**Issue by FraGoTe** [peruanosdev/playlist-quarantine-edition#13]
## Titulo de la charla 
Introducción a Machine Learning con Kaggle
## Descripcion
Creando mi primer modelo predictivo usando Python y ScikitLearn
## Enlace del video ( YouTube )
https://www.youtube.com/watch?v=5NHLaMgEi78

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
