### ISSUE TITLE
 How to create your custom slack app with Ruby

### ISSUE THREAD

**Issue by DanP1925** [peruanosdev/playlist-quarantine-edition#14]
## Título de la charla 
How to create your custom slack bot with Ruby

## Descripción
Debido al contexto actual los equipos de trabajo se han sido obligados a adaptar una forma de trabajo remota. Entre las herramientas que más se utilizan para comunicarse en equipos se encuentra Slack. Se puede aprovechar las apis que esta ofrece para automatizar procesos e interactuar con los miembros del equipo de una forma más organizada.
En esta charla voy a mostrar paso a paso como hice un bot de slack con ruby para automatizar el control de asistencia de mi oficina. Con eso explicaré:

- Como funcionan las apis de slack
- Como manejar requests con ruby mediante slack-ruby-client (https://github.com/slack-ruby/slack-ruby-client)
- Como modificar la respuestas del bot en slack mediante Slack Block Kit

## Enlace del video ( YouTube )
https://youtu.be/c0E-p72q4jQ

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
