### ISSUE TITLE
La clave está en ti y en el poder de tus ideas

### ISSUE THREAD

**Issue by lissavcasas** [peruanosdev/playlist-quarantine-edition#15]
## Título de la charla 
La clave está en ti y en el poder de tus ideas :sparkles:

## Descripción
¿Las personas de tu alrededor te hacen sentir que no puedes hacer algo?¿Tienes miedo de intentar algo nuevo?¿No tienes claro cuál es tu propósito en la vida?¿Tienes dudas de lo que eres capaz? Te invito a ver este video, donde comparto mi experiencia y algunos consejos que me han permitido romper diferentes barreras y prejuicios existentes para alcanzar mis metas, crecer como persona y lograr mi propósito en esta vida: _Ayudar a otras personas, construir interfaces de usuario y darles vida a través del código._ :yellow_heart:

La intención de esta charla es que puedas reflexionar, fortalezcas tu confianza y si es que aún no tienes un propósito en la vida, te pongas a pensar en ello y hagas eso que siempre has querido hacer. :heart:

## Enlace del video ( YouTube )
https://youtu.be/ZtGSDX-0ZVE

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
