### ISSUE TITLE
Dart: Herencia vs Composición

### ISSUE THREAD

**Issue by kranfix** [peruanosdev/playlist-quarantine-edition#16]
## Título de la charla 
Herencia vs Composición

## Descripción
Exploramos uno de los problemas de la programación orientada a objetos (OOP) al usar herencia y vemos cómo solucionarlo usando composición.

Para el ejemplo usamos Dart, puesto que nos permite explorarlo en web sin  necesidad de instalación alguna. No obstante, puedes probar el ejemplo en lenguajes como C++, Java, C#, JavaScript o cualquier lenguaje que use clases, pues todas sufren del mismo problema.

## Enlace del video ( YouTube )
https://youtu.be/WRnZuu2PIr4

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
