### ISSUE TITLE
Potenciando el uso de figma para el diseño de productos digitales

### ISSUE THREAD

**Issue by cnahuina** [peruanosdev/playlist-quarantine-edition#17]
## Título de la charla 
Potenciando el uso de figma para el diseño de productos digitales
## Descripción
Es un video donde hablo más que todo del uso de herramientas que nos van a permitir potenciar, acelerar el uso de figma para el diseño de productos digitales.
## Enlace del video ( YouTube )
https://youtu.be/oVm-2hYG8ZI

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
