### ISSUE TITLE
Aumentar la rapidez al tipear como jugando.

### ISSUE THREAD

**Issue by neosergio** [peruanosdev/playlist-quarantine-edition#18]
## Título de la charla 
Ideas durante CUARENTENA: Aumentar la rapidez al tipear como jugando.

## Descripción
Ideas para hacer durante la cuarentena: Aumentar la rapidez al tipear como jugando con estos 5 sitios web.

El Touch Typing te va a ayudar a optimizar tu tiempo de trabajo.

## Enlace del video ( YouTube )
https://www.youtube.com/watch?v=kOjd-Lr6X0Q&t=37s

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
