### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by jpgotopo** [peruanosdev/playlist-quarantine-edition#2]
El video tiene por intención dar las pautas para crear una página web, en este caso del video compartido se trata de la primera parte de un tutorial que he armado. Esta primera parte trata de cómo comenzar con Flutter Web (las configuraciones necesarias), asì también se instruirá cómo seccionar nuestro diseño web previamente hecho (Illustrator, Adobe XD u otros diseñadores de UI), al tiempo que estaremos dando pautas para hacer una página responsiva con Flutter.

Link: [https://youtu.be/2TNibHiEhJg](https://www.youtube.com/watch?v=2TNibHiEhJg)

Referencia: [https://flutter-es.io/web](https://flutter-es.io/web)

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
