### ISSUE TITLE
Construye un perfil ganador en Linkedin

### ISSUE THREAD

**Issue by dotconde** [peruanosdev/playlist-quarantine-edition#4]
## Titulo de la charla 
Construye un perfil ganador en Linkedin

## Descripcion
Aprende como construir paso a paso un perfil altamente efectivo en Linkedin que atraiga muchos seguidores y ofertas de trabajo. 

## Enlace del video ( YouTube )
https://www.youtube.com/watch?v=jx8VCnIkjLI

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
