### ISSUE TITLE
Testing in the frontend world

### ISSUE THREAD

**Issue by sergiodxa** [peruanosdev/playlist-quarantine-edition#5]
## Titulo de la charla 
Testing in the frontend world

## Descripción
Repaso por las diferentes formas y técnicas para hacer testings y darnos seguridad de que nuestra aplicación Frontend va a funcionar, empezando por linters, pasando por tippado, unit tests, snapshots, test de integración y terminando con end-to-end. Todo viendo ejemplo con código.

## Enlace del video ( YouTube )
https://www.youtube.com/watch?v=sOMAMtOBiA8

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
