### ISSUE TITLE
Funcionamiento de Arduino Nano: Proyecto CodeBreaker

### ISSUE THREAD

**Issue by Jhomalex** [peruanosdev/playlist-quarantine-edition#7]
## Titulo de la charla 
Funcionamiento de Arduino Nano: Proyecto CodeBreaker

## Descripcion
Funcionamiento d un Arduino Nano programado para requerir una autenticación mediante conexión Bluetooth para poder interactuar con diodos LEDs, registrar nuevos usuarios, editar o eliminar los datos de un usuario creado, cerrar sesión o apagar el LCD conectado al dispositivo.

## Enlace del video ( YouTube )
[Click aquí para ver el video en YouTube](https://www.youtube.com/watch?v=qnSeBblJkUU&t=64s)

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
