### ISSUE TITLE
APIs gratuitas para hacer aplicaciones. #YoMeQuedoEnCasa

### ISSUE THREAD

**Issue by neosergio** [peruanosdev/playlist-quarantine-edition#8]
## Titulo de la charla 
IDEAS durante la cuarentena: APIs para hacer apps #Coronavirus #Covid-19 #YoMeQuedoEnCasa - video 01

## Descripcion

Recomendación de APIs a usar para hacer aplicaciones mientras dura la cuarentena.

**Comment by hansyschmitt** [comment]
Hola Sergio, que genial tus charlas. 
No se si tendrás títulos alternativos mas cortos?

**Comment by neosergio** [comment]
Gracias Hansy :), tienes razón ahi te paso las versiones cortas.

Titulo del video: APIs gratuitas para hacer aplicaciones.

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
