### ISSUE TITLE
APIs para hacer aplicaciones de Pokemon #YoMeQuedoEnCasa

### ISSUE THREAD

**Issue by neosergio** [peruanosdev/playlist-quarantine-edition#9]
## Titulo de la charla 
IDEAS durante la cuarentena: APIs para hacer apps de Pokemon #Covid19 #YoMeQuedoEnCasa

## Descripcion
Ideas para hacer durante la cuarentena: APIs para hacer apps de Pokemon #Covid19 #YoMeQuedoEnCasa
PokeAPI, Pokemon GO API, Pokemon Trading Game Card.

## Enlace del video ( YouTube )
https://www.youtube.com/watch?v=ggamRbxZwyI

**Comment by neosergio** [comment]
Titulo del video: APIs para hacer aplicaciones de Pokemon

**Comment by darksy12** [comment]
Gracias por el video :D 
https://www.youtube.com/playlist?list=PLE6H0aE8p3mErQScYuTpE4hu8wOjN8Gua
